// <auto-generated />
namespace Person_Information_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addPersonAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPersonAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "202108080851109_addPersonAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
